<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18098" started-at="2021-12-08T05:10:36Z" finished-at="2021-12-08T05:10:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18098" started-at="2021-12-08T05:10:36Z" finished-at="2021-12-08T05:10:54Z">
      <class name="com.amazontestrunner.LoginpageTestRunnernew">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.amazontestrunner.LoginpageTestRunnernew@14acaea5]" name="setUp" is-config="true" duration-ms="8464" started-at="2021-12-08T10:40:36Z" finished-at="2021-12-08T10:40:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="AM_01()[pri:0, instance:com.amazontestrunner.LoginpageTestRunnernew@14acaea5]" name="AM_01" duration-ms="7360" started-at="2021-12-08T10:40:45Z" finished-at="2021-12-08T10:40:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is Not matching expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is Not matching expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.amazon.utils.Handlers.verifytitleOfpage(Handlers.java:464)
	at com.amazontestrunner.LoginpageTestRunnernew.AM_01(LoginpageTestRunnernew.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM_01 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.amazontestrunner.LoginpageTestRunnernew@14acaea5]" name="tearDown" is-config="true" duration-ms="2224" started-at="2021-12-08T10:40:52Z" finished-at="2021-12-08T10:40:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amazontestrunner.LoginpageTestRunnernew -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
